[package]
name = "ape-aerotelem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
eframe = "0.22.0"
plotters = "0.3.4"
plotters-backend = "0.3.4"
